/**
 * Turns Quintal's price list (.xlsx) into `scripts/quintal-catalog.data.ts`.
 *
 *   pnpm catalog:quintal <xlsx> [--out <path>] [--check]
 *
 * Any parse error exits 1 without writing. `--check` writes nothing and fails
 * when the committed data file differs from what the Excel and the overrides
 * produce now. Never touches the database.
 */

import { execFileSync } from "node:child_process";
import { createHash } from "node:crypto";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { basename, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { readXlsxSheet } from "./lib/xlsx-reader";
import { quintalOverrides } from "./quintal-catalog.overrides";
import { type ParseIssue, parseQuintalSheet } from "./quintal-catalog.parser";
import {
	QUINTAL_SHEET_NAME,
	type QuintalCatalog,
} from "./quintal-catalog.schema";

const repoRoot = fileURLToPath(new URL("..", import.meta.url));
const defaultOut = resolve(repoRoot, "scripts/quintal-catalog.data.ts");
const biomeBin = resolve(repoRoot, "node_modules/.bin/biome");

const usage =
	"Uso: pnpm catalog:quintal <archivo.xlsx> [--out scripts/quintal-catalog.data.ts] [--check]";

function parseArgs(argv: string[]) {
	let input: string | undefined;
	let out = defaultOut;
	let check = false;
	for (let index = 0; index < argv.length; index += 1) {
		const arg = argv[index];
		if (arg === "--check") check = true;
		else if (arg === "--out") {
			const value = argv[index + 1];
			if (!value) throw new Error(usage);
			out = resolve(value);
			index += 1;
		} else if (arg && !arg.startsWith("--") && !input) input = resolve(arg);
		else throw new Error(`Argumento inesperado "${arg}". ${usage}`);
	}
	if (!input) throw new Error(usage);
	return { input, out, check };
}

function renderModule(catalog: QuintalCatalog, outPath: string) {
	const source = [
		"// Generated by `pnpm catalog:quintal` from Quintal's price list. Do not edit:",
		"// change scripts/quintal-catalog.overrides.ts and regenerate.",
		'import type { QuintalCatalog } from "./quintal-catalog.schema";',
		"",
		`export const quintalCatalog: QuintalCatalog = ${JSON.stringify(catalog, null, "\t")};`,
		"",
	].join("\n");
	return execFileSync(
		biomeBin,
		["format", `--stdin-file-path=${relative(repoRoot, outPath)}`],
		{ cwd: repoRoot, input: source, encoding: "utf8" },
	);
}

function printIssues(issues: ParseIssue[]) {
	for (const issue of issues) {
		const row = issue.row === null ? "-" : String(issue.row);
		console.error(
			`${issue.severity.padEnd(7)} fila ${row.padStart(3)}  ${issue.code}: ${issue.message}`,
		);
	}
}

function main() {
	const { input, out, check } = parseArgs(process.argv.slice(2));
	const bytes = readFileSync(input);
	const sha256 = createHash("sha256").update(bytes).digest("hex");
	const sheet = readXlsxSheet(bytes, QUINTAL_SHEET_NAME);
	const result = parseQuintalSheet(sheet, quintalOverrides, {
		fileName: basename(input),
		sha256,
	});

	printIssues(result.issues);
	const kinds = new Map<string, number>();
	for (const entry of result.rowLog) {
		kinds.set(entry.kind, (kinds.get(entry.kind) ?? 0) + 1);
	}
	console.error(
		`Filas clasificadas: ${[...kinds].map(([kind, count]) => `${kind} ${count}`).join(", ")}`,
	);

	if (!result.catalog) {
		console.error("Hay errores: no se escribió el catálogo.");
		process.exitCode = 1;
		return;
	}

	const rendered = renderModule(result.catalog, out);
	const target = relative(repoRoot, out);
	if (check) {
		const current = existsSync(out) ? readFileSync(out, "utf8") : "";
		if (current !== rendered) {
			console.error(
				`${target} no coincide con la planilla y los overrides: regenerar con pnpm catalog:quintal.`,
			);
			process.exitCode = 1;
			return;
		}
		console.error(
			`${target} al día (${result.catalog.products.length} productos).`,
		);
		return;
	}

	writeFileSync(out, rendered);
	console.error(`${target}: ${result.catalog.products.length} productos.`);
}

try {
	main();
} catch (error) {
	console.error(error instanceof Error ? error.message : error);
	process.exitCode = 1;
}
