LABELS = {
    'spanish': {
        'cover_label': 'PROPUESTA COMERCIAL', 'page': 'Página', 'of': 'de',
        'document_label': 'Documento comercial', 'proposal_sheet': 'Ficha de propuesta',
        'field': 'Campo', 'detail': 'Detalle', 'client': 'Cliente', 'project': 'Proyecto',
        'version': 'Versión', 'issue_date': 'Fecha de emisión', 'validity': 'Vigencia',
        'status': 'Estado', 'source_version': 'Versión de fuente',
        'source_hash': 'SHA-256 de fuente', 'generated_at': 'Generado', 'contents': 'Contenido',
        'part_one': 'Parte I', 'commercial_proposal': 'Propuesta comercial',
        'executive_summary': 'Resumen ejecutivo', 'dimension': 'Dimensión', 'summary': 'Síntesis',
        'background': 'Antecedentes y entendimiento de la necesidad',
        'issues': 'Problemas y oportunidades identificados', 'objectives': 'Objetivos',
        'general_objective': 'Objetivo general', 'specific_objectives': 'Objetivos específicos',
        'success_indicators': 'Indicadores de éxito', 'indicator': 'Indicador',
        'target': 'Objetivo', 'verification': 'Verificación',
        'alternatives': 'Alternativas de solución', 'alternative': 'Alternativa',
        'duration': 'Duración', 'investment': 'Inversión', 'limits': 'Límites',
        'recommended_alternative': 'Alternativa recomendada',
        'scope': 'Alcance, exclusiones y supuestos', 'included_scope': 'Alcance incluido',
        'modules': 'Módulos incluidos', 'module': 'Módulo', 'capabilities': 'Capacidades',
        'limit': 'Límite', 'exclusions': 'Fuera de alcance',
        'assumptions': 'Supuestos y dependencias',
        'methodology': 'Metodología y gobierno del proyecto', 'practices': 'Prácticas de trabajo',
        'governance': 'Gobierno', 'role': 'Rol', 'responsibility': 'Responsabilidad',
        'cadence': 'Frecuencia', 'work_plan': 'Plan de trabajo, entregables e hitos',
        'plan_by_stages': 'Plan por etapas', 'stage': 'Etapa', 'activities': 'Actividades',
        'deliverables': 'Entregables', 'milestone': 'Hito', 'code': 'Código',
        'deliverable': 'Entregable', 'format': 'Formato', 'minimum_content': 'Contenido mínimo',
        'acceptance': 'Aceptación', 'technical_solution': 'Solución técnica u operativa',
        'technology_stack': 'Stack tecnológico preliminar', 'layer': 'Capa',
        'technology': 'Tecnología', 'notes': 'Observaciones',
        'nonfunctional': 'Requisitos no funcionales', 'security': 'Seguridad y continuidad',
        'quality': 'Calidad, pruebas y aceptación', 'testing': 'Estrategia de pruebas',
        'acceptance_process': 'Procedimiento de aceptación', 'warranty': 'Garantía',
        'team': 'Equipo de trabajo', 'dedication': 'Dedicación estimada', 'timeline': 'Cronograma',
        'start_condition': 'Condición de inicio', 'timing': 'Momento', 'validates': 'Valida',
        'dependencies': 'Dependencias', 'investment_payments': 'Inversión y esquema de pagos',
        'payment_schedule': 'Esquema de pagos', 'percentage': 'Porcentaje',
        'verifiable_condition': 'Condición verificable', 'commercial_terms': 'Condiciones comerciales',
        'validity_acceptance': 'Vigencia y aceptación comercial',
        'start_conditions': 'Condiciones de inicio', 'terms_part': 'Parte II',
        'terms_title': 'Términos y condiciones', 'signatures_part': 'Parte III',
        'signatures_title': 'Aceptación y firmas',
        'signatures_intro_1': 'Complete los campos para identificar la propuesta y versión aceptadas.',
        'signatures_intro_2': 'Los campos son controles editables de Word para completar antes de la firma acordada por las partes.',
        'acceptance_data': 'Datos de aceptación',
        'selected_scope': 'Alternativa o alcance seleccionado',
        'tax_id': 'CUIT / identificación fiscal',
        'authorized_representative': 'Representante autorizado', 'email': 'Correo electrónico',
        'acceptance_date': 'Fecha de aceptación', 'signatures': 'Firmas',
        'client_party': 'POR EL CLIENTE', 'quasar_party': 'POR INGENIERÍA QUASAR SRL',
        'organization': 'Organización', 'name': 'Nombre y apellido',
        'personal_id': 'DNI / identificación', 'date': 'Fecha', 'signature': 'Firma',
        'click_to_fill': 'Haga clic o toque aquí para completar',
        'insert_signature': 'Insertar firma electrónica o digital', 'change_part': 'Anexo A',
        'change_control': 'Control de cambios', 'procedure': 'Procedimiento',
        'base_form': 'Formulario base', 'request_number': 'Número de solicitud',
        'requester': 'Solicitante', 'description': 'Descripción',
        'scope_impact': 'Impacto en alcance', 'schedule_impact': 'Impacto en cronograma',
        'fees_impact': 'Impacto en honorarios', 'resolution': 'Resolución',
        'pending': 'Pendiente', 'proposal_option': 'Propuesta',
    },
    'english': {
        'cover_label': 'COMMERCIAL PROPOSAL', 'page': 'Page', 'of': 'of',
        'document_label': 'Commercial document', 'proposal_sheet': 'Proposal details',
        'field': 'Field', 'detail': 'Detail', 'client': 'Client', 'project': 'Project',
        'version': 'Version', 'issue_date': 'Issue date', 'validity': 'Valid through',
        'status': 'Status', 'source_version': 'Source version', 'source_hash': 'Source SHA-256',
        'generated_at': 'Generated', 'contents': 'Contents', 'part_one': 'Part I',
        'commercial_proposal': 'Commercial proposal', 'executive_summary': 'Executive summary',
        'dimension': 'Dimension', 'summary': 'Summary',
        'background': 'Background and understanding of the need',
        'issues': 'Identified problems and opportunities', 'objectives': 'Objectives',
        'general_objective': 'Overall objective', 'specific_objectives': 'Specific objectives',
        'success_indicators': 'Success indicators', 'indicator': 'Indicator', 'target': 'Target',
        'verification': 'Verification', 'alternatives': 'Solution alternatives',
        'alternative': 'Alternative', 'duration': 'Duration', 'investment': 'Investment',
        'limits': 'Limits', 'recommended_alternative': 'Recommended alternative',
        'scope': 'Scope, exclusions, and assumptions', 'included_scope': 'Included scope',
        'modules': 'Included modules', 'module': 'Module', 'capabilities': 'Capabilities',
        'limit': 'Limit', 'exclusions': 'Out of scope',
        'assumptions': 'Assumptions and dependencies',
        'methodology': 'Methodology and project governance', 'practices': 'Working practices',
        'governance': 'Governance', 'role': 'Role', 'responsibility': 'Responsibility',
        'cadence': 'Cadence', 'work_plan': 'Work plan, deliverables, and milestones',
        'plan_by_stages': 'Stage plan', 'stage': 'Stage', 'activities': 'Activities',
        'deliverables': 'Deliverables', 'milestone': 'Milestone', 'code': 'Code',
        'deliverable': 'Deliverable', 'format': 'Format', 'minimum_content': 'Minimum content',
        'acceptance': 'Acceptance', 'technical_solution': 'Technical or operational solution',
        'technology_stack': 'Preliminary technology stack', 'layer': 'Layer',
        'technology': 'Technology', 'notes': 'Notes',
        'nonfunctional': 'Non-functional requirements', 'security': 'Security and continuity',
        'quality': 'Quality, testing, and acceptance', 'testing': 'Testing strategy',
        'acceptance_process': 'Acceptance process', 'warranty': 'Warranty',
        'team': 'Project team', 'dedication': 'Estimated allocation', 'timeline': 'Schedule',
        'start_condition': 'Start condition', 'timing': 'Timing', 'validates': 'Validated by',
        'dependencies': 'Dependencies', 'investment_payments': 'Investment and payment schedule',
        'payment_schedule': 'Payment schedule', 'percentage': 'Percentage',
        'verifiable_condition': 'Verifiable condition', 'commercial_terms': 'Commercial terms',
        'validity_acceptance': 'Validity and commercial acceptance',
        'start_conditions': 'Start conditions', 'terms_part': 'Part II',
        'terms_title': 'Terms and conditions', 'signatures_part': 'Part III',
        'signatures_title': 'Acceptance and signatures',
        'signatures_intro_1': 'Complete the fields to identify the accepted proposal and version.',
        'signatures_intro_2': 'The fields are editable Word controls to complete before the signature method agreed by the parties.',
        'acceptance_data': 'Acceptance details', 'selected_scope': 'Selected alternative or scope',
        'tax_id': 'Tax identification', 'authorized_representative': 'Authorized representative',
        'email': 'Email', 'acceptance_date': 'Acceptance date', 'signatures': 'Signatures',
        'client_party': 'FOR THE CLIENT', 'quasar_party': 'FOR INGENIERÍA QUASAR SRL',
        'organization': 'Organization', 'name': 'Full name',
        'personal_id': 'Personal identification', 'date': 'Date', 'signature': 'Signature',
        'click_to_fill': 'Click or tap here to complete',
        'insert_signature': 'Insert electronic or digital signature', 'change_part': 'Appendix A',
        'change_control': 'Change control', 'procedure': 'Procedure', 'base_form': 'Base form',
        'request_number': 'Request number', 'requester': 'Requester',
        'description': 'Description', 'scope_impact': 'Scope impact',
        'schedule_impact': 'Schedule impact', 'fees_impact': 'Fees impact',
        'resolution': 'Resolution', 'pending': 'Pending', 'proposal_option': 'Proposal',
    },
}
